name: chatbotFinanzautoV2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - langgraph==0.4.2
      - langchain==0.3.25
      - redis==5.0.0
      - pymilvus==2.5.8
      - docker
      - pymongo==4.11.3
      - fastapi==0.115.12
      - uvicorn==0.34.2
      - pydantic==2.11.0
      - python-jose==3.4.0
      - passlib==1.7.4
      - python-multipart==0.0.20
      - cryptography==44.0.3
      - bcrypt==4.3.0
      - prometheus-client==0.21.1
      - opentelemetry-api==1.21.0
      - opentelemetry-sdk==1.21.0
      - structlog==23.2.0
      - pytest==7.4.3
      - pytest-asyncio==0.23.2
      - pytest-cov==4.1.0
      - python-dotenv==1.0.1
      - pyyaml==6.0.1
      - tenacity==8.2.3
      - black==23.11.0
      - isort==5.12.0
      - flake8==6.1.0
      - mypy==1.7.1
      - mkdocs==1.5.3
      - mkdocs-material==9.4.14
      - numpy==1.26.2
      - pandas==2.1.3
      - opentelemetry-instrumentation==0.42b0
      - python-logging-loki==0.3.1
      - boto3
