redis:
  memory:
    # Configuración para persistencia
    save:
      - seconds: 900  # 15 minutos
        changes: 1
      - seconds: 300  # 5 minutos
        changes: 10
      - seconds: 60   # 1 minuto
        changes: 10000
    
    # Políticas de memoria
    maxmemory: 2gb
    maxmemory-policy: volatile-lru
    
    # Configuración de snapshots
    snapshot:
      enabled: true
      interval: 3600  # 1 hora
      
    # Configuración de réplicas
    replication:
      enabled: true
      replicas: 2